// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgQCfqKlCx83iGbnluiE6vDBj4uEat0Hs',
    appId: '1:265212839817:web:376eeb61cf7f6c5f4cc358',
    messagingSenderId: '265212839817',
    projectId: 'fir-testing-a3afb',
    authDomain: 'fir-testing-a3afb.firebaseapp.com',
    storageBucket: 'fir-testing-a3afb.appspot.com',
    measurementId: 'G-C8M9YCSWLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4sHoZkU1xESyc6MOcuYHL5hU3F7-ynEU',
    appId: '1:265212839817:android:17181ce9f67453b44cc358',
    messagingSenderId: '265212839817',
    projectId: 'fir-testing-a3afb',
    storageBucket: 'fir-testing-a3afb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKY691o0D5YIjWLPUQftIe6pcaXBlUimw',
    appId: '1:265212839817:ios:f9fd91571b04c1cd4cc358',
    messagingSenderId: '265212839817',
    projectId: 'fir-testing-a3afb',
    storageBucket: 'fir-testing-a3afb.appspot.com',
    iosBundleId: 'com.example.riceapi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKY691o0D5YIjWLPUQftIe6pcaXBlUimw',
    appId: '1:265212839817:ios:4f79d29d9ab6ef7c4cc358',
    messagingSenderId: '265212839817',
    projectId: 'fir-testing-a3afb',
    storageBucket: 'fir-testing-a3afb.appspot.com',
    iosBundleId: 'com.example.riceapi.RunnerTests',
  );
}
